// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rydvzpbzfnnwqtjhyucs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5ZHZ6cGJ6Zm5ud3F0amh5dWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTIyMzcsImV4cCI6MjA3MDc2ODIzN30.srcd3ke3mG_RQi9E77bAi_mnhpRF6p-7A3jsbecZdgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});